### PR TITLE
Compatibility issues corrected

### PR DESCRIPTION
**Pull request by Joanguitar**
-Modified the open5gs dependency to the main nextepc repository since open5gs lacks the autoconf files.
-Included an older srsLTE version that works with the lte virtualization of ue and enb.

### CODE REVIEW

**Comment by ravens** [comment]
Thanks for the PR! Your fix is actually reverting to nextEPC instead of Open5GS which is not bad, but I think we should stick to the latest code (i.e. Open5GS). I will integrate your PR this week in a nextEPC specific branch, and have another branch with Open5GS.

**Comment by ravens** [comment]
@Joanguitar I just did fix the master branch with latest Open5GS, if you wanna try.

**Comment by Joanguitar** [comment]
Thank you for considering my changes, I tried the new version and it still doesn't work, it fails on creating the tun_srsue interface in the ue docker. I fixed it by simply copying the additional folder I included in the virtual-UE-eNB folder and the line changed in the DockerFile from that same folder.
I hope it helps.
Thank you.

**Comment by ravens** [comment]
Oh interesting - I don’t managed to reproduce that problem - could you send me the actual log of the docker-compose up ? Make sure you rebuild with docker-compose build —no-cache.

**Comment by ravens** [comment]
Ok managed to reproduce, one of my machine was using an old branch of faux_rf. Using the commit you were trying to PR (5d82f19988bc148d7f4cec7a0f29184375a64b40) it works. I also reshape the repo to support ZeroMQ RF. Take a look ?

**Comment by Joanguitar** [comment]
Sure,

That sounds great, I'll take a look soon.

Best regards.

**Pull request closed without merging**
